name: travel_bucket_list
description: A new Flutter project.

publish_to: 'none' # Remove this line if you are publishing the package.

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add other dependencies here, if needed
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2
  hive: ^2.2.3
  image_picker: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/paris.jpg
    - assets/images/app_logo.jpg
    - assets/images/tokyo.jpg
    - assets/images/sydney.jpg
    - assets/images/cairo.jpg
    - assets/images/dubai.jpg
    - assets/images/london.jpg
    - assets/images/new_york.jpg
